//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningPlanner_1._0._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int IDosoby { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
    }
}
